### ISSUE TITLE
What version does 1.0.4 in hex correspond to in the repo?

### ISSUE THREAD

**Issue by vorce** [silviucpp/ezlib#3]
I'd like to try out ezlib in an elixir project, and used the latest version from https://hex.pm/packages/ezlib - however I'm not sure what version that corresponds to in the repo. The master README uses `ezlib:new` which is not present in the version from hex.

Would it be possible to get a hex release of what's in master?

**Comment by silviucpp** [comment]
Hello,

If you look careful are 2 different projects. This one is not in hex. the one in hex is from P1 .

Silviu

**Comment by vorce** [comment]
Oh wow, my bad -- sorry about the confusion.
